version = 0.1

[default]
[default.global.parameters]
stack_name = "eleknowledge-ai-dev"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "eleknowledge-ai"
region = "us-east-1"
image_repositories = []
disable_rollback = false
parameter_overrides = [
    "Environment=development",
    "ProjectName=EleKnowledge-AI"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[production]
[production.global.parameters]
stack_name = "eleknowledge-ai-prod"

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "eleknowledge-ai"
region = "us-east-1"
image_repositories = []
disable_rollback = false
parameter_overrides = [
    "Environment=production",
    "ProjectName=EleKnowledge-AI"
]
